# .github/ISSUE_TEMPLATE/title_format.yml
name: Title Format Only
description: 제목 형식만 안내하는 이슈 템플릿입니다.
title: "[TYPE] 이슈 제목을 여기에 작성"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        제목을 `[TYPE] 이슈 제목을 여기에 작성` 형식에 맞게 작성해주세요.

  - type: input
    id: dummy
    attributes:
      label: (선택 사항) 본문 내용이 있다면 작성해주세요
      placeholder: 내용이 없다면 비워두셔도 됩니다.
    validations:
      required: false
