# .github/ISSUE_TEMPLATE/title_format.yml
name: Title Format Only
description: 제목 형식만 안내하는 이슈 템플릿입니다.
title: "[TYPE] 이슈 제목을 여기에 작성"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        제목을 `[TYPE] 이슈 제목을 여기에 작성` 형식에 맞게 작성해주세요.
